### ISSUE TITLE
Update to `Phoenix 1.7`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-liveview-realtime-cursor-tracking-tutorial#34]
There is already a PR open https://github.com/dwyl/phoenix-liveview-realtime-cursor-tracking-tutorial/pull/31 by @dependabot
but it's failing. We need to follow the upgrade instructions to get this working with `1.7` ... ⏳

**Comment by LuchoTurtle** [comment]
Isn't this already implemented? 
https://github.com/dwyl/phoenix-liveview-realtime-cursor-tracking-tutorial/blob/26b1d795952b3e27fe0bbcfedb4fcb27581060d7/mix.exs#L46

**Comment by nelsonic** [comment]
Yeah, I made the changes myself manually yesterday: https://github.com/dwyl/phoenix-liveview-realtime-cursor-tracking-tutorial/pull/31/commits/a543d5e4a3135de35e049649549e7079c8484dfa 👨‍💻 
Had just opened this issue to capture my work. 👌 
(Thanks for the reminder to close it....) ✅
