### ISSUE TITLE
Deploy on Fly to test with multiple cursors!

### ISSUE THREAD

**Issue by SimonLab** [dwyl/phoenix-liveview-realtime-cursor-tracking-tutorial#4]
I just tried the `initial-implementation` branch, and it seems to work so far.
Once the branch is merged we can try to deploy the application on Fly.io for us to be able to test with multiple clients (at the moment i'm using multiple tabs in the browser)

**Comment by nelsonic** [comment]
Agreed. Definitely needs to be deployed to showcase. 👌
